<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFWXXoM7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFWXXoM7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFWXXoM7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFWXXoM7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFWXXoM7\App_KernelDevDebugContainer([
    'container.build_hash' => 'FWXXoM7',
    'container.build_id' => '82a32373',
    'container.build_time' => 1579785210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFWXXoM7');
