<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXFKpxbE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXFKpxbE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXFKpxbE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXFKpxbE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXFKpxbE\App_KernelDevDebugContainer([
    'container.build_hash' => 'XFKpxbE',
    'container.build_id' => '40d26b8a',
    'container.build_time' => 1579769871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXFKpxbE');
