<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container97nTvWk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container97nTvWk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container97nTvWk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container97nTvWk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container97nTvWk\App_KernelDevDebugContainer([
    'container.build_hash' => '97nTvWk',
    'container.build_id' => 'f9307e77',
    'container.build_time' => 1578471831,
], __DIR__.\DIRECTORY_SEPARATOR.'Container97nTvWk');
